### ISSUE TITLE
FakeHttpContext is Locking/Overriding other context created

### ISSUE THREAD

**Issue by Binu-Qburst** [vadimzozulya/FakeHttpContext#12]

**Comment by vadimzozulya** [comment]
@Binu-Qburst , could you please elaborate on this. It would be great to have a code sample to reproduce the issue :)

**Comment by vadimzozulya** [comment]
@VPrasadS, please use this issue instead of #13 (maybe you have a code sample ? :) )

**Comment by vadimzozulya** [comment]
Please, reopen with more details if necessary.
