### ISSUE TITLE
How to set up for querystring parameters

### ISSUE THREAD

**Issue by gswartz777** [vadimzozulya/FakeHttpContext#15]
I'm trying to test a controller method that makes uses of Request.QueryString parameters.  But when it gets to that line it bombs with Request being null.

```
if (Request.QueryString["WeekEnding"] != null)
{
    weekEnding = DateTime.Parse(Request.QueryString["WeekEnding"]);
}
```

Here is my test.  How do I set it up so that Request is not null and the querystring parameters are readable?

```
using (new FakeHttpContext.FakeHttpContext() { Uri = new Uri("http://asdfasdf.com?WeekEnding=1/1/19") })
{
    HttpContext.Current.Session.Add("UserKey", 1);
    HttpContext.Current.Session.Add("JobID", 1);

    var service = new Mock<ITimesheetService>();
    var otc = new Mock<IOnlineTimesheetController>();

    otc.Setup(x => x.GetTimesheetByJobId(It.IsAny<int>(), It.IsAny<DateTime>(), true)).Returns(new OnlineTimesheet() { TimeSheetId = 1 });

    var controller = new TimesheetController(service.Object, otc.Object);
    var results = controller.Index() as ViewResult;

    otc.Verify(x => x.GetTimesheetByJobId(1, It.IsAny<DateTime>(), true), Times.Once);
    Assert.IsNotNull(results);
}
```

**Comment by gswartz777** [comment]
If I added System.Web.HttpContext.Current. to the Request.QueryString lines it works however I've read that that is highly discouraged.  Instead they said to use this.HttpContext but when I do that it comes back null.  Not sure how to resolve that.

**Comment by vadimzozulya** [comment]
Hi @gswartz777, both `this.Request` or `this.HttpContext` are properties of the controller, and do not need the `HttpContect.Current` to be mocked. Have you tried this  https://stackoverflow.com/questions/970198/how-to-mock-the-request-on-controller-in-asp-net-mvc for MVC, or this https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/unit-testing-controllers-in-web-api for API controllers?

**Comment by gswartz777** [comment]
The first link would be most applicable to my situation, but it looks like that basically bypasses the need for your FakeHttpContext since it's mocking it on it's own, right?

**Comment by vadimzozulya** [comment]
Exactly! 😊 The tool is created mostly for legacy WebForm-based solutions, which is not possible (for any reason) to refactor to use `HttpContextBase` or replace with MVC/Web API controllers.

**Comment by vadimzozulya** [comment]
Please, reopen, if you have any questions.
