### ISSUE TITLE
System.Threading.SynchronizationLockException 

### ISSUE THREAD

**Issue by cyvocross** [vadimzozulya/FakeHttpContext#18]
Issue appear randomly, on asp net MVC .Net Framework 4.8 and Xunit :

    System.AggregateException : System.Threading.SynchronizationLockException : The object's synchronisation method was called from an unsynchronised block of code.

 SwitcherContainer.Dispose()
FakeHttpContext.Dispose()
<Create_billing_from_stream_request_should_be_successfull>d__5.MoveNext() ligne 198
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<<InvokeTestMethodAsync>b__1>d.MoveNext() ligne 264
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<AggregateAsync>d__4.MoveNext() ligne 48
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<RunAsync>d__9.MoveNext() ligne 90
----- Inner Stack Trace -----
FakeHostEnvironment.Dispose()
<>c__DisplayClass5_0.<Dispose>b__0(IDisposable x)

Workarround that seems to be working : 

`using (var ctx = new FakeHttpContext())
 {
        lock (ctx)
        {
              ......
        }
}`

**Comment by vadimzozulya** [comment]
Hi @cyvocross, thanks for the report, and sorry for the issue. Could you please post the whole test so I can reproduce the issue? And which version of XUnit do you have?

**Comment by vadimzozulya** [comment]
Please reopen with the code sample if necessary.
