### ISSUE TITLE
Sign so can use from Gac'd assembly

### ISSUE THREAD

**Issue by dazinator** [vadimzozulya/FakeHttpContext#6]
Hi There,
Thank you for a very useful library, works like a charm.

Any chance you could sign this assembly? I am in a scenario where I am having to resort to usage from the GAC, which requires that my dependencies are signed.

**Comment by dazinator** [comment]
PR submitted

**Comment by dazinator** [comment]
Do you plan to release on nuget.org anytime soon?

**Comment by dazinator** [comment]
Oh my bad - I see you have released this already! Thanks

**Comment by vadimzozulya** [comment]
Sorry that did not notify you.
